#!/usr/bin/env python3
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'results/phase2'
def fmt(v,d=3):
 if pd.isna(v): return 'NOT AVAILABLE'
 if isinstance(v,(float,np.floating)): return str(int(round(v))) if d==0 else f'{v:.{d}f}'
 return str(v)
def lead(r,x,d):
 ids=r.loc[r.phase2_decision.eq(d),'candidate']; q=x[x.candidate.isin(ids)].sort_values(['evidence_score','candidate'],ascending=[False,True]); return 'NONE' if q.empty else str(q.iloc[0].candidate)
x=pd.read_csv(OUT/'candidate_evidence_matrix.tsv',sep='\t',low_memory=False); r=pd.read_csv(OUT/'phase2_readiness.tsv',sep='\t'); lo=pd.read_csv(OUT/'loocv_candidate_stability.tsv',sep='\t')
e=pd.read_csv(OUT/'candidate_mouse_effects.tsv',sep='\t'); s=e.groupby('candidate').effect_value.agg(n_positive=lambda z:(z>0).sum(),n_negative=lambda z:(z<0).sum(),n_zero_or_undetermined=lambda z:(z==0).sum()).reset_index(); s['n_mice_effects']=s[['n_positive','n_negative','n_zero_or_undetermined']].sum(axis=1); s['majority_direction']=np.where(s.n_positive>s.n_negative,'positive',np.where(s.n_negative>s.n_positive,'negative','balanced')); s['majority_direction_fraction']=s[['n_positive','n_negative']].max(axis=1)/s.n_mice_effects; s['two_sided_direction_strength']=2*(s.majority_direction_fraction-.5).abs(); dc=list(s.columns[1:]); lo=lo.drop(columns=[c for c in dc if c in lo]).merge(s,on='candidate',how='left'); lo.to_csv(OUT/'loocv_candidate_stability.tsv',sep='\t',index=False)
bio=pd.read_csv(OUT/'interaction_biological_audit.tsv',sep='\t',low_memory=False); ids=x.sort_values('evidence_score',ascending=False).head(20)[['candidate']]; bio.merge(ids,on='candidate').to_csv(OUT/'top20_biological_audit.tsv',sep='\t',index=False)
lg,lh=lead(r,x,'GO'),lead(r,x,'HOLD'); tr=x[x.candidate.eq(lh)]; top=tr.iloc[0] if len(tr) else None; rr=r[r.candidate.eq(lh)]; lr=rr.iloc[0] if len(rr) else None; tl=lo[lo.candidate.eq(lh)]; tl=tl.iloc[0] if len(tl)==1 else None; holds=r[r.phase2_decision.eq('HOLD')][['candidate']].merge(x,on='candidate').sort_values(['evidence_score','candidate'],ascending=[False,True]).head(3)
L=['# Phase 1.5 final report','',f'Leading GO: {lg}',f'Leading HOLD: {lh}','']
if lg=='NONE': L+=['No candidate passes every closed Phase 2 readiness gate.','']
L+=['## 1. Executive summary','',f'No candidate passes every closed Phase 2 readiness gate. The leading HOLD hypothesis is **{lh}**, classified as {fmt(top.candidate_type)}. This is an observational prioritization and does not establish causality or therapeutic benefit.','','## 2. Dataset and inferential unit','','GSE324375 is analysed with the HTO-demultiplexed mouse as the inferential unit; cells represent sampling depth, not independent replication.','','## 3. Leading candidate','',f'Candidate: {lh}',f'Candidate class: {fmt(top.candidate_type)}',f'Evidence score: {fmt(top.evidence_score,4)}','Phase 2 decision: HOLD','','## 4. Animal-level replication','']
if tl is None: L+=['Informative-mouse summary: NOT AVAILABLE.','Reason: the leading candidate is not represented in the predeclared LOOCV/mouse-effect summary universe.','']
else:
 L += [f'Informative mice: {fmt(tl.n_mice,0)}.',f'Expected causal direction: {fmt(top.expected_direction)}.']
 if str(top.expected_direction)=='UNRESOLVED': L += ['Hypothesis-supporting mice: NOT APPLICABLE.','Hypothesis-opposing mice: NOT APPLICABLE.',f'Positive mouse effects: {fmt(tl.n_positive,0)}.',f'Negative mouse effects: {fmt(tl.n_negative,0)}.',f'Zero/undetermined effects: {fmt(tl.n_zero_or_undetermined,0)}.',f'Majority direction: {fmt(tl.majority_direction)}.',f'Majority direction fraction: {fmt(tl.majority_direction_fraction)}.',f'Two-sided direction strength: {fmt(tl.two_sided_direction_strength)}.']
 else: L += [f'Hypothesis-supporting mice: {fmt(tl.n_mice_supporting,0)}.',f'Hypothesis-opposing mice: {fmt(tl.n_mice_opposing,0)}.',f'Direction consistency: {fmt(tl.direction_consistency)}.']
 L += [f'Median mouse effect: {fmt(top.mouse_effect_median,4)}.',f'IQR: {fmt(top.mouse_effect_IQR,4)}.','']
L+=['## 5. LOOCV robustness','']+([f'LOOCV stability: {fmt(top.LOOCV_stability)}.','Candidate-specific folds remove one informative mouse and recalculate eligibility and competitive ranking.',''] if pd.notna(top.LOOCV_stability) else ['LOOCV stability: NOT AVAILABLE.','Reason: candidate-specific folds are unavailable.',''])
L+=['## 6. Permutation null','']+([f'Empirical p-value: {fmt(top.empirical_p,6)}.',f'Empirical FDR: {fmt(top.empirical_FDR,6)}.',f'Null percentile: {fmt(top.null_percentile)}.'] if pd.notna(top.empirical_p) else ['Empirical p-value: NOT AVAILABLE.','Empirical FDR: NOT AVAILABLE.','Null percentile: NOT AVAILABLE.'])+['The null is candidate-specific and does not establish biological causality.','']
L+=['## 7. Multimodal evidence','',f'RNA evidence: {fmt(top.RNA_evidence)}.',f'ADT evidence: {fmt(top.ADT_evidence)}.',f'Data-driven state evidence: {fmt(top.data_driven_state_evidence)}.','These modalities support prioritization but do not establish causality.','','## 8. External perturbation evidence','',f'Status: {fmt(top.external_perturbation_support)}.','Independent system-matched perturbation evidence is required before causal interpretation.','','## 9. Biological validity','',f'Entity type: {fmt(top.entity_type)}.',f'Mechanism class: {fmt(top.mechanism_class)}.',f'Interaction validity: {fmt(top.interaction_validity)}.',f'Valid for mechanistic ranking: {fmt(top.valid_for_mechanistic_ranking)}.',f'Biological reinterpretation: {fmt(top.biological_reinterpretation)}.','','## 10. Mechanistic chain','']
cc=[c for c in x if c.startswith('chain_')]
if cc:
 for c in cc: L.append(f"{c.replace('chain_','').replace('_',' ').title()}: {fmt(top[c])}.")
 L += [f'Mechanistic evidence coherence: {fmt(top.mechanistic_evidence_coherence)}.','']
else: L += ['Mechanistic-chain evidence: NOT AVAILABLE.','']
L += ['## 11. Leading HOLD hypotheses','']
for i,z in enumerate(holds.itertuples(),1): L.append(f'{i}. {z.candidate} — class={fmt(z.candidate_type)}; score={fmt(z.evidence_score,4)}; decision=HOLD.')
for i in range(len(holds)+1,4): L.append(f'{i}. NOT AVAILABLE — no additional candidate selected.')
def rf(n): return 'NOT AVAILABLE' if lr is None or n not in r else fmt(lr[n])
L += ['','## 12. Why the leading candidate remains HOLD','',f"Statistical status: {rf('statistical_status')}.",f"Biological status: {rf('biological_status')}.",f"Mechanistic status: {rf('mechanistic_status')}.",f"Experimental status: {rf('experimental_status')}.",f"LOOCV status: {rf('LOOCV_status')}.",f"Null status: {rf('null_status')}.",f"External evidence status: {rf('external_evidence_status')}.",f"Decision reason: {rf('decision_reason')}.",'','## 13. Experimental validation','','Use candidate-class-specific perturbation of source/signal and receptor/target arms, matched controls and rescue where feasible. Measure activation, viability, abundance and tumor-cell killing.','','## 14. Falsifiers','','- Independent perturbations do not reproduce the effect.','- Rescue fails.','- The phenotype is explained by viability, abundance or generic stress.','- Tumor-killing effects do not track perturbation.','- Independent replication fails.','','## 15. Limitations','','The discovery remains observational and does not establish causality or therapeutic benefit.','Residual treatment, batch, cell-composition and abundance effects may contribute.','Spatial contact, longitudinal validation and direct perturbational causality are not established.','','## 16. Reproducibility','','Random seed: 17.','Permutations: 1000.','Inferential unit: mouse.','LOOCV universe: predeclared priority candidates.','Primary dataset: GSE324375.','Contextual/external datasets: GSE289772; GSE314342 as recorded by the pipeline.','','## 17. Final decision','',f'{lh} remains HOLD. The current evidence supports experimental prioritization, not causal or therapeutic claims.','']
(OUT/'PHASE1_FINAL_REPORT.md').write_text('\n'.join(L)+'\n')
T=['# TOP 3 candidates','',f'Leading GO: {lg}',f'Leading HOLD: {lh}','']+[f'{i}. {z.candidate} — class={fmt(z.candidate_type)}; score={fmt(z.evidence_score,4)}; decision=HOLD.' for i,z in enumerate(holds.itertuples(),1)]+[f'{i}. NOT AVAILABLE — no additional candidate selected.' for i in range(len(holds)+1,4)]
(OUT/'TOP3_candidates.md').write_text('\n'.join(T)+'\n')
print(f'Post-ranking summary complete; leading HOLD={lh}')
